"""
run_summarize_PI_modelLevel.py
----------------------------
Execution script to aggregate and rank feature importance metrics on a per-model basis, 
consolidating results from multiple spatial cross-validation folds.

Input data:
1. Raw importance logs (CSV) generated by spatial feature importance pipelines, containing per-fold importance scores 
    (e.g., Haversine Skill Score drops).

Generates and saves:
1. Model-level Consensus Datasets (CSV) aggregating cross-validated importance ranks for each model-method combination, 
    including median ranks and min/max ranges.
2. Stability Summary Plots (PNG): Compact dot plots showing the median consensus rank for top features 
    (capped at 30) with asymmetric error bars representing the ranking range across all folds, annotated 
    with model-specific shorthand labels (e.g., 'R', 'X', 'S') to visualize ranking divergence across different model types.
"""


import os

# Import the function from our newly created module
from feature_importance.functions.summarize_PI_modelLevel import calculate_rank_consensus

# ---------------------------------------------------------
# Define Paths
# ---------------------------------------------------------
INPUT_BASE_DIR = r"C:\Users\wande\Documents\Bioinformatics_2mas_2025-2026\Master_Thesis\Pcode\feature_importance\output\PI"
OUTPUT_BASE_DIR = r"C:\Users\wande\Documents\Bioinformatics_2mas_2025-2026\Master_Thesis\Pcode\feature_importance\output\PI\PI_ModelLevel_summaries"

# ---------------------------------------------------------
# Define Scope
# ---------------------------------------------------------
METHODS_TO_SUMMARIZE = [
    "permutation", 
    "conditional_permutation"
]

MODELS_USED = [
    "RandomForest", 
    "XGBoost", 
    "SVM"
]

if __name__ == "__main__":
    
    # Execute the pipeline
    calculate_rank_consensus(
        input_base=INPUT_BASE_DIR,
        output_base=OUTPUT_BASE_DIR,
        methods=METHODS_TO_SUMMARIZE,
        models=MODELS_USED
    )