"""
post_analysis_functions.py
----------------------------
Functions script to calculate univariate Moran's I and aggregate the already-ranked loadings from PCA, sPCA, and MAF into comparative summary tables.

Input data:
1. Preprocessed numerical feature datasets and corresponding spatial coordinates.
2. Previously generated ranked feature loading CSV files from unsupervised pipelines (PCA, sPCA, MAF).

Generates and saves:
1. Univariate Moran's I score tables for all features, calculating spatial autocorrelation using a row-standardized Gabriel graph (CSV).
2. Comparative summary tables pivoting the top N feature loadings across PCA, sPCA, and MAF methods for each spatial/principal component (CSV).
"""

import os
import numpy as np
import pandas as pd
import libpysal

def calculate_all_morans_i(X_processed: pd.DataFrame, coords_df: pd.DataFrame, out_base_dir: str, data_name: str):
    """
    Calculates univariate Moran's I for all features using a row-standardised Gabriel graph.
    Saves to: <out_base_dir>/Morans_I/<data_name>/<prefix>_univariate_morans_i.csv
    """
    print(f"    [+] Calculating Moran's I for {data_name}...")
    
    # Create file prefix (e.g., "sI" or "tX_Betula")
    file_prefix = data_name.replace("/", "_").replace("\\", "_")
    
    coords = coords_df.values.astype(float).copy()
    if coords_df.duplicated(keep=False).any():
        rng = np.random.default_rng(seed=42)
        coords = coords + rng.uniform(-1e-4, 1e-4, size=coords.shape)
        
    w_gabriel = libpysal.weights.Gabriel(coords)
    W_binary, _ = w_gabriel.full()
    
    row_sums = W_binary.sum(axis=1, keepdims=True)
    row_sums[row_sums == 0] = 1 
    W_row_norm = W_binary / row_sums

    results = []
    for col in X_processed.columns:
        z = X_processed[col].values
        z = z - z.mean()
        var = np.sum(z**2)
        
        if var > 0:
            I = (z.T @ W_row_norm @ z) / var
        else:
            I = 0.0
            
        results.append({
            "Feature": col, 
            "Morans_I": I
        })
        
    df_i = pd.DataFrame(results).sort_values("Morans_I", ascending=False)
    
    out_folder = os.path.join(out_base_dir, "Morans_I", data_name)
    os.makedirs(out_folder, exist_ok=True)
    
    # Save with prefix
    file_name = f"{file_prefix}_univariate_morans_i.csv"
    df_i.to_csv(os.path.join(out_folder, file_name), index=False)


def generate_top_loadings_summary(in_base_dir: str, out_base_dir: str, data_name: str, n_top: int = 5):
    """
    Reads the existing ranked_loadings.csv files from in_base_dir generated by the 
    unsupervised pipeline and pivots them into a single summary table per component.
    """
    print(f"Compiling top {n_top} loadings summary for {data_name}...")
    
    # Create file prefix (e.g., "sI" or "tX_Betula")
    file_prefix = data_name.replace("/", "_").replace("\\", "_")
    
    methods = ["PCA", "sPCA", "MAF"]
    components = ["Comp1", "Comp2"] 
    
    out_folder = os.path.join(out_base_dir, "Loadings_ranking_summary", data_name)
    os.makedirs(out_folder, exist_ok=True)
    
    for comp in components:
        summary_dict = {"Rank": list(range(1, n_top + 1))}
        
        for method in methods:
            # GRAB from the original unsupervised models directory using the prefixed filename
            csv_path = os.path.join(in_base_dir, method, data_name, "tables", f"{file_prefix}_ranked_loadings.csv")
            
            if not os.path.exists(csv_path):
                print(f"      [!] Warning: Missing {method} {file_prefix}_ranked_loadings.csv for {data_name}")
                summary_dict[method] = [np.nan] * n_top
                continue
            
            df = pd.read_csv(csv_path)
            df_comp = df[df["Component"] == comp].sort_values("Rank")
            
            top_features = []
            for _, row in df_comp.head(n_top).iterrows():
                feat = row['Feature']
                val = row['Actual_Loading']
                top_features.append(f"{feat} ({val:+.3f})")
            
            while len(top_features) < n_top:
                top_features.append(np.nan)
                
            summary_dict[method] = top_features
            
        summary_df = pd.DataFrame(summary_dict).set_index("Rank")
        
        # Save with prefix
        file_name = f"{file_prefix}_top_{n_top}_loadings_{comp}.csv"
        summary_df.to_csv(os.path.join(out_folder, file_name))